project:
  type: book
  output-dir: ../docs
  resources: ["images/"]

book:
  title: "Dinâmicas de Aprendizado em Cenários de Incertezas de Mercado"
  author: 
    - "André Vitor Pereira de Melo"
    - "Fábio Junior Clemente Gama"
  description: "uma aplicação de teoria dos jogos com Expereince-Weighted Attraction"
  date: "2025-09-13"
  language: pt
  reader-mode: true         # ← ativa o botão de “modo leitura”
  sidebar:
    tools:                  # ← ícones abaixo do título (barra esquerda)
      - icon: github
        text: "GitHub"
        href: https://github.com/SEU-USUARIO/EWA-MarketDynamics
  chapters:
    - index.qmd
    - epigrafe.qmd
    - part: "Capítulos"
      chapters:
        - 01-introducao.qmd
        - 02-referencial-teorico.qmd
        - 03-metodologia.qmd
        - 04-resultados.qmd
        - 05-conclusao.qmd
        - 99-referencias.qmd
  appendices:
    - apendice-a.qmd
    - apendice-b.qmd

format:
  html:
    theme: cosmo
    mainfont: "Source Serif 4"
    monofont: "Fira Code"
    toc: true
    number-sections: true
    code-fold: show
    lang: pt
    css: [styles/book.scss, styles/styles.css]

suppress-bibliography: true
bibliography: referencias.bib
csl: _extensions/abnt/abnt.csl

execute:
  echo: false
  warning: false
  message: false
  freeze: false

knitr:
  opts_chunk:
    fig.align: "center"
    fig.width: 7
    fig.height: 4.5
    dpi: 300
