project:
  type: book
  output-dir: ../docs
  resources: ["images/"]

book:
  title: "Dinâmicas de Aprendizado em Cenários de Incertezas de Mercado"
  author: 
    - "André Vitor Pereira de Melo"
    - "Fábio Junior Clemente Gama"
  description: "uma aplicação de teoria dos jogos com Expereince-Weighted Attraction"
  date: "2025-09-13"
  language: pt
  reader-mode: true         # ativa o botão de “modo leitura”
  sidebar:
    tools:                  # ícones abaixo do título (barra esquerda)
      - icon: github
        text: "GitHub"
        href: https://github.com/drewmelo/EWA-MarketDynamics
  chapters:
    - index.qmd
    - epigrafe.qmd
    - part: "Capítulos"
      chapters:
        - 01_introducao.qmd
        - 02_referencial_teorico.qmd
        - 03_metodologia.qmd
        - 04_aplicacao_modelo_simulacao.qmd
        - 05_resultados.qmd
        - 06_conclusao.qmd
        - 99_referencias.qmd
  appendices:
    - apendice.qmd

format:
  html:
    theme:
      - cosmo
      - styles/book.scss
    css: styles/styles.css
    mainfont: "Source Serif 4"
    monofont: "Fira Code"
    toc: true
    number-sections: true
    code-fold: show
    lang: pt

suppress-bibliography: true
bibliography: referencias.bib
csl: _extensions/abnt/abnt.csl

execute:
  echo: false
  warning: false
  message: false
  freeze: false

knitr:
  opts_chunk:
    fig.align: "center"
    fig.width: 7
    fig.height: 4.5
    dpi: 300
